steps:
    # build the container image
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/web:$SHORT_SHA", "."]
      # push the container image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/web:$SHORT_SHA"]
      # Deploy container image to Cloud Run
    - name: "gcr.io/cloud-builders/gcloud"
      args:
        [
          "beta",
          "run",
          "deploy",
          "$BRANCH_NAME",
          "--image=gcr.io/$PROJECT_ID/web:$SHORT_SHA",
          "--memory=1G",
          "--region=us-central1",
          "--platform=managed",
          "--allow-unauthenticated",
          "--set-env-vars", "apiKey=berglas://berglas-secrets-$PROJECT_ID/apiKey",
          "--set-env-vars", "authDomain=berglas://berglas-secrets-$PROJECT_ID/authDomain",
          "--set-env-vars", "databaseURL=berglas://berglas-secrets-$PROJECT_ID/databaseURL", 
          "--set-env-vars", "projectId=berglas://berglas-secrets-$PROJECT_ID/projectId", 
          "--set-env-vars", "storageBucket=berglas://berglas-secrets-$PROJECT_ID/storageBucket",
          "--set-env-vars", "messagingSenderId=berglas://berglas-secrets-$PROJECT_ID/messagingSenderId",
          "--set-env-vars", "appId=berglas://berglas-secrets-$PROJECT_ID/appId",
          "--set-env-vars", "measurementId=berglas://berglas-secrets-$PROJECT_ID/measurementId",
          "--set-env-vars", "type=berglas://berglas-secrets-$PROJECT_ID/type",
          "--set-env-vars", "project_id=berglas://berglas-secrets-$PROJECT_ID/project_id",
          "--set-env-vars", "private_key_id=berglas://berglas-secrets-$PROJECT_ID/private_key_id",
          "--set-env-vars", "private_key=berglas://berglas-secrets-$PROJECT_ID/private_key",
          "--set-env-vars", "client_email=berglas://berglas-secrets-$PROJECT_ID/client_email",
          "--set-env-vars", "client_id=berglas://berglas-secrets-$PROJECT_ID/client_id",
          "--set-env-vars", "auth_uri=berglas://berglas-secrets-$PROJECT_ID/auth_uri",
          "--set-env-vars", "token_uri=berglas://berglas-secrets-$PROJECT_ID/token_uri",
          "--set-env-vars", "auth_provider_x509_cert_url=berglas://berglas-secrets-$PROJECT_ID/auth_provider_x509_cert_url",
          "--set-env-vars", "client_x509_cert_url=berglas://berglas-secrets-$PROJECT_ID/client_x509_cert_url",
        ]
  images:
    - gcr.io/$PROJECT_ID/web