steps:
    # build the container image
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/plexus-prediction-service:$SHORT_SHA", "."]
      # push the container image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/plexus-prediction-service:$SHORT_SHA"]
      # Deploy container image to Cloud Run
    - name: "gcr.io/cloud-builders/gcloud"
      args:
        [
          "beta",
          "run",
          "deploy",
          "$BRANCH_NAME",
          "--image=gcr.io/$PROJECT_ID/plexus-prediction-service:$SHORT_SHA",
          "--memory=1G",
          "--region=us-central1",
          "--platform=managed",
          "--allow-unauthenticated",
          "--set-env-vars=BLURRED_BUCKET_NAME=<BLURRED_BUCKET_NAME>"
          ]
  images:
    - gcr.io/$PROJECT_ID/plexus-prediction-service